### ISSUE TITLE
address bar changes stay active until restart

### ISSUE THREAD

**Issue by mozbhearsum** [bwinton/whimsy#11]
13:13 < bhearsum> so, i uninstalled a jetpack recently (whimsy), and it continued to affect behaviour in the addressbar until i restarted - is that indicative of a 
                  platform bug?
13:15 @Mossop It is most likely indicative of the jetpack using direct chrome access and not cleaning up after itself properly

13:15 < irving> bwinton: if you don
13:15 < irving> don't undo everything in your addon's uninstall method, it will stick around until restart

**Comment by bwinton** [comment]
This should be fixed by the switch to a WebExtension, so I'm closing it out.  Thanks!
