### ISSUE TITLE
Add-on appears to be corrupt

### ISSUE THREAD

**Issue by Nolski** [bwinton/whimsy#110]
When I try to install whimsy on FF 36 and 38 (in safe mode as well), I get the error: `the add-on downloaded from github.com could not be installed because it appears to be corrupt`

Is anyone else having this same issue?

**Comment by bwinton** [comment]
I started getting that too.  Fortunately, it's on AMO now, so we should all probably get it from https://addons.mozilla.org/en-US/firefox/addon/whimsycorn/ instead…
(Leaving this open in case someone wants to debug the actual problem.)

**Comment by bwinton** [comment]
The size looked wrong, so I re-deployed, and it seems like this has been fixed.
