### ISSUE TITLE
Use of CPOW's tripping about:performance

### ISSUE THREAD

**Issue by mayankleoboy** [bwinton/whimsy#119]
https://dutherenverseauborddelatable.wordpress.com/2015/05/06/detecting-slow-add-ons/

I tried this, and Whimsy pro is one of the addons that has >0 CPW usage.
It would probably be better to remove them completely.

**Comment by bwinton** [comment]
Sounds great!  But I know almost nothing about CPOWs.  Can you send a pull-request that shows me how to get rid of them, or even just where they are?

**Comment by mayankleoboy** [comment]
I have no idea either!  I am just  a nightly tester.
I would say the best bet is to contact :yoric , :mconley or  :krizsa

**Comment by bwinton** [comment]
I'm pretty sure the upcoming switch to a WebExtension will fix this, so I'mma close this bug…  😉
