### ISSUE TITLE
Replace Google doodle when in Private Browsing mode

### ISSUE THREAD

**Issue by mikeconley** [bwinton/whimsy#120]
With this: http://imgur.com/jCxpBrW

Via: http://www.reddit.com/r/funny/comments/368xl5/this_should_be_googles_logo_when_you_open_it_in/

**Comment by bwinton** [comment]
That feels a little too mean-spirited towards a competitor for my taste, I think…

**Comment by mikeconley** [comment]
Oh - wasn't meant to be mean spirited towards Google at all; was meant to add more backdrop to the state-of-play as it were for Private Browsing mode, like the wedding rings. :)

But alright, willing to close.
