### ISSUE TITLE
Randomly replace "This might void your warranty!"

### ISSUE THREAD

**Issue by strugee** [bwinton/whimsy#122]
Every time you load `about:config`, Whimsy should randomly select one of the following and replace the warranty line with it:
- "This might void your warranty!" (i.e. don't change anything)
- "This gun is loaded!"
- "Here be dragons!" (from the en-GB version, apparently)
- Etc.

See also https://bugzilla.mozilla.org/show_bug.cgi?id=446704

**Comment by bwinton** [comment]
We can't do this as a WebExtension, so I think I'm going to close this bug.  Thanks for the idea, though! 🙂
