### ISSUE TITLE
Whimsy disabled in latest nightlies because not signed

### ISSUE THREAD

**Issue by Flore-mozfr** [bwinton/whimsy#134]
In the latest nightlies (for a few days already), non signed addons are disabled (previously, there was only a warning)...
I don't know when this will land in release channel, but right now I feel m browser lacks this touch of whimsy it had.
Name 	Firefox
Version 	42.0a1
Build ID 	20150809030213

**Comment by mikeconley** [comment]
There is a signed version of Whimsy here: https://addons.mozilla.org/en-US/firefox/addon/whimsycorn/

**Comment by bwinton** [comment]
On the one hand, I think we want to get more people using the addons.mozilla.org version of Whimsy that @mikeconley pointed to, so I don't really want to fix this bug.  But on the other hand, it would be nice to show people how to sign their own add-ons, so maybe we want to try signing this one ourselves or something…

I think I'm going to lean towards pointing people at the official AMO version, and close this bug.  But thank you for the issue!
