### ISSUE TITLE
Where's my burger?

### ISSUE THREAD

**Issue by mythmon** [bwinton/whimsy#28]
On Linux. I had the burger before potch's better burger patch. Then I upraded, and nothing changed. So I disabled and re-enabled the burger feature. For my efforts, all icons were removed from the button, leaving it a few pixel wide blank space. After a restart of the browser, the burger toggle in whimsy does nothing. Screenshot for proof. Noticed how the box is checked, and my burger is missing.

![shot_8994](https://f.cloud.github.com/assets/305049/903581/5baf7636-fbae-11e2-91b7-1edabfe6966d.png)

**Comment by bwinton** [comment]
We can't do this as a WebExtension, so the feature is going away.  :cry:
On the plus side, that means I can close this bug…  😉
