### ISSUE TITLE
Javascript exception during shutdown

### ISSUE THREAD

**Issue by irvingreid** [bwinton/whimsy#58]
The add-on manager catches a JS exception in Whimsy's 'shutdown' bootstrap method:

**\* LOG addons.xpi: Calling bootstrap method shutdown on jid1-6mUPixNFCjAgkg@jetpack version 0.16
console.error: whimsy:
DOMException
- prototype DOMExceptionPrototype
  - ABORT_ERR = 20
  - DATA_CLONE_ERR = 25
  - DOMSTRING_SIZE_ERR = 2
  - HIERARCHY_REQUEST_ERR = 3
  - INDEX_SIZE_ERR = 1
  - INUSE_ATTRIBUTE_ERR = 10
  - INVALID_ACCESS_ERR = 15
  - INVALID_CHARACTER_ERR = 5
  - INVALID_MODIFICATION_ERR = 13
  - INVALID_NODE_TYPE_ERR = 24
  - INVALID_STATE_ERR = 11
  - NAMESPACE_ERR = 14
  - NETWORK_ERR = 19
  - NOT_FOUND_ERR = 8
  - NOT_SUPPORTED_ERR = 9
  - NO_DATA_ALLOWED_ERR = 6
  - NO_MODIFICATION_ALLOWED_ERR = 7
  - QUOTA_EXCEEDED_ERR = 22
  - SECURITY_ERR = 18
  - SYNTAX_ERR = 12
  - TIMEOUT_ERR = 23
  - TYPE_MISMATCH_ERR = 17
  - URL_MISMATCH_ERR = 21
  - VALIDATION_ERR = 16
  - WRONG_DOCUMENT_ERR = 4
  - code = 1
  - columnNumber = 0
  - data = null
  - filename = resource://gre/modules/XPIProvider.jsm -> jar:file:///Users/ireid/Library/Application%20Support/Firefox/Profiles/sngia9xd.debug/extensions/jid1-6mUPixNFCjAgkg@jetpack.xpi!/bootstrap.js -> resource://gre/modules/commonjs/toolkit/loader.js -> resource://jid1-6mupixnfcjagkg-at-jetpack/whimsy/lib/throbber.js
  - inner = null
  - lineNumber = 34
  - location = {"language":2,"languageName":"JavaScript","filename":"resource://gre/modules/XPIProvider.jsm -> jar:file:///Users/ireid/Library/Application%20Support/Firefox/Profiles/sngia9xd.debug/extensions/jid1-6mUPixNFCjAgkg@jetpack.xpi!/bootstrap.js -> resource://gre/modules/commonjs/toolkit/loader.js -> resource://jid1-6mupixnfcjagkg-at-jetpack/whimsy/lib/throbber.js","name":"stop","lineNumber":34,"sourceLine":null,"caller":{"language":2,"languageName":"JavaScript","filename":"resource://gre/modules/XPIProvider.jsm -> jar:file:///Users/ireid/Library/Application%20Support/Firefox/Profiles/sngia9xd.debug/extensions/jid1-6mUPixNFCjAgkg@jetpack.xpi!/bootstrap.js -> resource://gre/modules/commonjs/toolkit/loader.js -> resource://jid1-6mupixnfcjagkg-at-jetpack/whimsy/lib/throbber.js","name":"exports.unload","lineNumber":43,"sourceLine":null,"caller":{"language":2,"languageName":"JavaScript","filename":"resource://gre/modules/XPIProvider.jsm -> jar:file:///Users/ireid/Library/Application%20Support/Firefox/Profiles/sngia9xd.debug/extensions/jid1-6mUPixNFCjAgkg@jetpack.xpi!/bootstrap.js -> resource://gre/modules/commonjs/toolkit/loader.js -> resource://jid1-6mupixnfcjagkg-at-jetpack/whimsy/lib/main.js","name":"exports.onUnload","lineNumber":70,"sourceLine":null,"caller":{"language":2,"languageName":"JavaScript","filename":"resource://gre/modules/XPIProvider.jsm -> jar:file:///Users/ireid/Library/Application%20Support/Firefox/Profiles/sngia9xd.debug/extensions/jid1-6mUPixNFCjAgkg@jetpack.xpi!/bootstrap.js -> resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/system/unload.js","name":"unload/<","lineNumber":58,"sourceLine":null,"caller":{"language":2,"languageName":"JavaScript","filename":"resource://gre/modules/XPIProvider.jsm -> jar:file:///Users/ireid/Library/Application%20Support/Firefox/Profiles/sngia9xd.debug/extensions/jid1-6mUPixNFCjAgkg@jetpack.xpi!/bootstrap.js -> resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/system/unload.js","name":"unload","lineNumber":56,"sourceLine":null,"caller":{"language":2,"languageName":"JavaScript","filename":"resource://gre/modules/XPIProvider.jsm -> jar:file:///Users/ireid/Library/Application%20Support/Firefox/Profiles/sngia9xd.debug/extensions/jid1-6mUPixNFCjAgkg@jetpack.xpi!/bootstrap.js -> resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/system/unload.js","name":"onunload","lineNumber":77,"sourceLine":null,"caller":{"language":2,"languageName":"JavaScript","filename":"resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/system/events.js","name":null,"lineNumber":74,"sourceLine":null,"caller":{"language":2,"languageName":"JavaScript","filename":"resource://gre/modules/XPIProvider.jsm -> jar:file:///Users/ireid/Library/Application%20Support/Firefox/Profiles/sngia9xd.debug/extensions/jid1-6mUPixNFCjAgkg@jetpack.xpi!/bootstrap.js -> resource://gre/modules/commonjs/toolkit/loader.js","name":"unload","lineNumber":457,"sourceLine":null,"caller":{"language":2,"languageName":"JavaScript","filename":"resource://gre/modules/XPIProvider.jsm -> jar:file:///Users/ireid/Library/Application%20Support/Firefox/Profiles/sngia9xd.debug/extensions/jid1-6mUPixNFCjAgkg@jetpack.xpi!/bootstrap.js","name":"shutdown","lineNumber":296,"sourceLine":null,"caller":{"language":2,"languageName":"JavaScript","filename":"resource://gre/modules/XPIProvider.jsm","name":"XPI_callBootstrapMethod","lineNumber":4184,"sourceLine":null,"caller":{"language":2,"languageName":"JavaScript","filename":"resource://gre/modules/XPIProvider.jsm","name":"shutdownObserver","lineNumber":2006,"sourceLine":null,"caller":{"language":2,"languageName":"JavaScript","filename":"chrome://global/content/globalOverlay.js","name":"goQuitApplication","lineNumber":44,"sourceLine":null,"caller":{"language":2,"languageName":"JavaScript","filename":"chrome://browser/content/browser.xul","name":"oncommand","lineNumber":1,"sourceLine":null,"caller":{"language":0,"languageName":"C++","filename":null,"name":null,"lineNumber":0,"sourceLine":null,"caller":null}}}}}}}}}}}}}}
  - message = Index or size is negative or greater than the allowed amount
  - name = IndexSizeError
  - result = 2152923137
- prototype Object

**Comment by bwinton** [comment]
I'm pretty sure switching to a WebExtension will fix this, so I'm closing this bug. 😉
