### ISSUE TITLE
Add back the classic cookie description

### ISSUE THREAD

**Issue by strugee** [bwinton/whimsy#6]
A long time ago, cookies were described as delicious in the Options/Preferences pane, or something like that. Whimsy should totally restore this.

**Comment by strugee** [comment]
Just found this while trawling through my oldest open GitHub issues :joy:

Sad as it is to say, I don't think the ability to do this is forthcoming in WebExtensions... so we should probably close :(

**Comment by bwinton** [comment]
Yeah. I can kinda understand why Mozilla doesn't want add-on authors to be able to change those pages (the possibility of abuse is _way_ too high), but that does mean that we won't be able to do this.

Thanks for the idea, though!

**Comment by strugee** [comment]
Heh, any time. Thanks for maintaining Whimsy through the years :-)
