### ISSUE TITLE
Replace "Hello" speech bubble icon with Lionel Ritchie face

### ISSUE THREAD

**Issue by madhavaenros** [bwinton/whimsy#91]
I.e., like ![this](https://pbs.twimg.com/media/Bu8U1boIIAEg0cw.jpg)

**Comment by mikeconley** [comment]
See https://github.com/bwinton/whimsy/pull/116

**Comment by bwinton** [comment]
We can't do this as a WebExtension, and Hello doesn't really exist anymore, so I'mma close this bug…  😉
